### ISSUE TITLE
Crash when i try to upgrade troops

### ISSUE THREAD

**Issue by OfficialKitkat** [admiralnelson/bannerlord-error-detector#4] opened 2020-07-07 16:28 UTC
Hello. So im new to the whole modding community. Just downloaded my first mods and it crashed when i tryed to upgrade a unit. Anyone that could se the problem in this code since im new to this i have no idea what to really look for or what caused the issue in the first place :D thanks!

Also it asked me if i wanted to download the error bug but it just makes it a google chrome link and cant add it here. Maybe this will work

![5a06ad50e2a120ade7d9e902fa08274e](https://user-images.githubusercontent.com/67970177/86812741-a5026a80-c07f-11ea-9083-f5545991c381.png)

**Comment by admiralnelson** [comment] 2020-07-07 16:56
Hello

From the error message I read, The error was caused by Party Screen Enhancement. I am not the guy who developed/maintaining that mod. You should send the error page, installed mods list, with your save file to corresponding mod author instead. Here’s the mod author GitHub repository https://github.com/Hirtol/PartyScreenEnhancements


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by OfficialKitkat** [comment] 2020-07-07 17:44
Okey thank you alot!

________________________________
Från: admiralnelson <notifications@github.com>
Skickat: den 7 juli 2020 18:57
Till: admiralnelson/bannerlord-error-detector <bannerlord-error-detector@noreply.github.com>
Kopia: OfficialKitkat <mc.lillrossie@live.com>; Author <author@noreply.github.com>
Ämne: Re: [admiralnelson/bannerlord-error-detector] Crash when i try to upgrade troops (#4)


Hello

From the error message I read, The error was caused by Party Screen Enhancement. I am not the guy who developed/maintaining that mod. You should send the error page, installed mods list, with your save file to corresponding mod author instead. Here’s the mod author GitHub repository https://github.com/Hirtol/PartyScreenEnhancements


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by admiralnelson** [comment] 2020-07-07 17:45
No problem. I will close this issue

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Closed as completed** 2020-07-07 17:45 UTC
